version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
init:
- cmd: choco install gitversion.portable -pre -version 4.0.0-beta0011
build_script:
- cmd: fake.cmd
test: off
artifacts:  
- path: ./artifacts/**/*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/psampaio-ci/api/v2/package
  api_key:
    secure: EvLaBeK1OVNnO6/7ZOm6nAUh8kMETA8n0UGhx+rWmCz7LowAqNBquXL+Q3xoBGVB
  skip_symbols: true
  on:
    branch: master